package bbs

// taglines is the /tl pool: BBS-style one-liners, heavy on mesh/LoRa/radio
// puns. Keep each under ~120 bytes so a tagline is always one radio chunk.
var taglines = []string{
	// LoRa & RF
	"Long Range, short tempers",
	"My spreading factor is 12 and so is my patience",
	"Gain is temporary, ground plane is forever",
	"-120 dBm and vibing",
	"Chirp happens",
	"Spread spectrum, not rumors",
	"My other antenna is a coat hanger",
	"SWR: Standing Wave Regrets",
	"Free-space path loss is not a personal failing",
	"dBi or not dBi, that is the question",
	"Stay out of my Fresnel zone",
	"It's not dead air, it's duty cycle",
	"915 MHz and I still can't reach you emotionally",
	"Feedline losses, friendship gains",
	"My VSWR is fine, thanks for asking",
	"Impedance is futile: 50 ohms assimilates all",
	"Antenna up, expectations down",
	"Polarization is a lifestyle choice",
	"I peaked in the 33cm band",
	"Line of sight is a state of mind",
	"A dipole a day keeps the silence away",
	"Coax: expensive string",
	"The best antenna is the one you actually mounted",
	"Radiate responsibly",
	"My link budget is in the red but my heart is full",
	"Wavelength: about yea long",
	"Attenuation happens to the best of us",
	"You can't spell LoRa without... okay you basically can",
	"Real hams count in dB",
	"E and H fields forever entangled, like us",
	// Mesh
	"Three hops for the elven kings under the sky",
	"Store and forward, like grandma's fruitcake",
	"Flood routing: gossip, but structured",
	"It takes a village to route a packet",
	"Your packet took the scenic route",
	"Hop count is just a suggestion",
	"I relay, therefore I am",
	"Meshing around since day one",
	"Be the repeater you wish to see in the world",
	"A packet in the air is worth two in the queue",
	"Every node is a backbone if you believe hard enough",
	"Ad hoc? More like ad awesome",
	"TTL: Time To Leave",
	"My route is flapping and honestly so am I",
	"Self-healing network, self-hurting sysop",
	"Decentralize your feelings",
	"Where we're going, we don't need infrastructure",
	"Packets want to be free (of collisions)",
	"The mesh provides",
	"Friends don't let friends run single points of failure",
	"In hops we trust",
	"Zero bars, full mesh",
	"Off-grid but on-topic",
	"The internet is down; the mesh abides",
	"Route around damage, including emotional",
	"My neighbor table is fuller than my fridge",
	"Everything is a repeater if you're brave enough",
	"Topology is destiny",
	"Small mesh, big dreams",
	"One node is loneliness, two nodes is a network",
	"Broadcast like nobody's listening (they aren't)",
	"Think globally, mesh locally",
	"Good fences make good RF neighbors",
	"Latency is just packets taking time to smell the roses",
	"I've got adverts older than your node",
	"Not all who wander are lost; some are flood-routed",
	"United we mesh, divided we... also mesh",
	"There's no place like ::1, but the mesh comes close",
	"Keep calm and carry a spare node",
	"What happens on the mesh stays on the mesh (plus retransmits)",
	// BBS nostalgia
	"NO CARRIER",
	"+++ATH0 yourself",
	"Handles are forever, phone lines are not",
	"All my friends are in the node list",
	"This tagline stolen from a better BBS",
	"300 baud: read along at home",
	"Please deposit 25 cents for the next packet",
	"ANSI art is not a crime",
	"Door games open 24/7, propagation permitting",
	"Your call is important to us: you are caller #42",
	"Leave mail for the sysop, get a free tagline",
	"Running on a Pi and a prayer",
	"As seen on FidoNet (citation needed)",
	"Zmodem crashed so you don't have to",
	"Now with 100% fewer phone bills",
	"Busy signal nostalgia club: members 1",
	"Upload ratio enforced by vibes",
	"Press any key. No, not that one.",
	"If you can read this, the modem gods smiled",
	"56k in my heart, 0.3k on the air",
	"The sysop is asleep. The sysop is always asleep.",
	"Hang up and try your call again... forever",
	"This node achieves elite status after dark",
	"War-dialing the sky",
	"BBS: Bytes Between Summits",
	"Logging off is just logging on somewhere else",
	"Saved by the bell character",
	"My handle survived four decades and two hard drive crashes",
	"We had chatrooms at home; the chatroom was one line",
	"Carrier detected. Heart rate elevated.",
	"A/S/L? Amplitude, SNR, Location",
	"Still waiting for my turn on the single phone line",
	"Textfiles were my social media",
	"This BBS ran on a 286 and it was glorious",
	"You've got mesh mail",
	// Ham & radio culture
	"73, but make it mesh",
	"CQ CQ CQ, duty cycle permitting",
	"Elmers wanted, apply within",
	"QRP: Quietly Radiating Patience",
	"My shack is a ziploc bag on a mast",
	"Antennas: the original social network",
	"Ragchew responsibly",
	"QSL cards accepted, packets preferred",
	"Every day is Field Day when your gear lives outside",
	"The ionosphere called; it says hi",
	"Skywarn? I barely know warn",
	"Grounding: electrical and emotional",
	"My noise floor has a mezzanine",
	"Signal report: 5 by fine",
	"Worked all neighbors (WAN)",
	"DX is just mesh with extra steps",
	"Contesting sleep since 1979",
	"You should hear my other rig",
	"Morse is just very slow LoRa",
	"Rig here is five watts and a dream",
	// Hardware & solar
	"Powered by an 18650 and optimism",
	"Solar node: works great at night*",
	"Heltec: because your soldering iron missed you",
	"ESP32 dreams of electric sheep",
	"My node survived winter. My battery didn't.",
	"Weatherproof until proven otherwise",
	"That's not corrosion, that's patina",
	"IP67: Ingress Probably 67%",
	"One more node and the HOA loses it",
	"The mast is duct tape all the way down",
	"Deep sleep: the node, not the sysop",
	"3.3 volts of pure ambition",
	"Brownout detected (node and sysop)",
	"My roofline is 40% antenna by weight",
	"Silicone sealant is a love language",
	"U.FL connectors: tiny, fragile, like my hopes",
	"Battery at 12%: thoughts and prayers",
	"It compiles at -40C, ship it",
	"GPS lock achieved, life lock pending",
	"There is no cloud, just other people's nodes on hills",
	"Tower climbing: cheaper than therapy, scarier too",
	"My BOM is longer than my resume",
	"Mount high, solder low",
	"Perfboard is permanent enough",
	// SNR & propagation
	"-19 dB and still talking smack",
	"RSSI: Really Sad Signal Indicator",
	"Heard you 3 dB above the noise, loved every bit",
	"Propagation: it's complicated",
	"If the SNR is rising, so is my mood",
	"Multipath: for when one path isn't enough drama",
	"Noise floor? I live in the noise basement",
	"Fading is temporary, logs are forever",
	"Inversion layer? In THIS economy?",
	"Rain fade builds character",
	"My signal bounces off things you wouldn't believe",
	"Knife-edge diffraction, butter-smooth delivery",
	"Trees eat 915 for breakfast",
	"Terrain is just spicy free space",
	"Anomalous propagation, nominal enthusiasm",
	"The duct giveth and the duct taketh away",
	// Packets & protocol
	"This message chunked for your protection",
	"140 bytes ought to be enough for anybody",
	"ACKs are a love language",
	"Dropped packets tell no tales",
	"Retransmission: the sincerest form of flattery",
	"CRC error: Can't Really Complain",
	"My favorite frame? The one that arrived.",
	"Half-duplex, full heart",
	"Every ACK is a tiny hug from physics",
	"Best-effort delivery, best-effort everything",
	"Jitter is my cardio",
	"Sequence numbers keep me regular",
	"I've seen frames you people wouldn't believe",
	"All frames are beautiful (that pass checksum)",
	"Backoff exponentially, dream linearly",
	"Payloads before egos",
	"Encrypted, encapsulated, emotionally available",
	"Say it with checksums",
	"Idempotent and proud",
	"Some packets just want to watch the airtime burn",
	// Meta & misc
	"Insert witty tagline here (lost in transit)",
	"Tagline delayed due to atmospheric conditions",
	"This tagline traveled 3 hops to disappoint you",
	"Certified airtime-neutral tagline",
	"Tagline of the day, results may vary by elevation",
	"If found, please return this tagline to the noise floor",
	"Warning: tagline may contain traces of packet loss",
	"This space intentionally left terse",
	"Brought to you by 130 bytes and stubbornness",
	"No taglines were harmed in this transmission (two were dropped)",
	"Live from a rooftop near you",
	"As heard on 906.875 MHz",
	"Your RF exposure today: one (1) pun",
	"Batteries not included, hills sold separately",
	"Objects in mesh are farther than they appear",
	"Some assembly required. Some disassembly, eventually.",
	"Void where prohibited by terrain",
	"Results not typical; typical results are silence",
	"Now in glorious 7-bit ASCII",
	"Handcrafted artisanal packets, small-batch routed",
}
